# Generated by Django 4.2.25 on 2025-11-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=16),
        ),
    ]
